// compose compiler stability

// immutable collection interfaces
kotlin.collections.List
kotlin.collections.Map
kotlin.collections.Set
kotlin.collections.Collection

// immutable metadata time types
java.time.LocalDateTime
java.time.LocalDate
java.time.Duration

// immutable provider models
com.music.innertube.models.**

// immutable database models
com.example.musicfy.db.entities.**
